---
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    augeasproviders_core: https://github.com/voxpupuli/puppet-augeasproviders_core
    augeasproviders_shellvar: https://github.com/voxpupuli/puppet-augeasproviders_shellvar
